import keyMirror from 'keymirror';

export default keyMirror({
  GET_PORTFOLIO_KPI: null,
  GET_PORTFOLIO_KPI_START: null,
  GET_PORTFOLIO_KPI_SUCCESS: null,
  GET_PORTFOLIO_KPI_FAILURE: null,
  GET_PRIMARY_KPI_FOR_ALL_FACILITIES: null,
  GET_PRIMARY_KPI_FOR_ALL_FACILITIES_START: null,
  GET_PRIMARY_KPI_FOR_ALL_FACILITIES_SUCCESS: null,
  GET_PRIMARY_KPI_FOR_ALL_FACILITIES_FAILURE: null,
  GET_COMPARISON_KPI_FOR_ALL_FACILITIES: null,
  GET_COMPARISON_KPI_FOR_ALL_FACILITIES_START: null,
  GET_COMPARISON_KPI_FOR_ALL_FACILITIES_SUCCESS: null,
  GET_COMPARISON_KPI_FOR_ALL_FACILITIES_FAILURE: null,
  RESET_COMPARISON_KPI_FOR_FACILITIES: null,
  RESET_PRIMARY_KPI_FOR_FACILITIES: null,
  SELECT_PORTFOLIO_KPI: null
});
