import keyMirror from 'keymirror';

export default keyMirror({
  LOAD_CONTRACT_FILE_START: null,
  LOAD_CONTRACT_FILE_SUCCESS: null,
  LOAD_CONTRACT_FILE_FAILURE: null,

  LOAD_UTILITY_CONTRACT_START: null,
  LOAD_UTILITY_CONTRACT_SUCCESS: null,
  LOAD_UTILITY_CONTRACT_FAILURE: null
});
