import keyMirror from 'keymirror';

export default keyMirror({
  LOAD_APPLICATION_GROUPINGS_START: null,
  LOAD_APPLICATION_GROUPINGS_SUCCESS: null,
  LOAD_APPLICATION_GROUPINGS_FAILURE: null,

  RESET_APPLICATION_GROUPINGS: null,
  RESET_DEFAULT_APPLICATION_ROUTE: null,

  SET_DEFAULT_APPLICATION_ROUTE: null
});
