import keyMirror from 'keymirror';

export const UTILITY_DEMAND_GET_LAST = 'UTILITY_DEMAND_GET_LAST';
export const UTILITY_DEMAND_GET_CURRENT = 'UTILITY_DEMAND_GET_CURRENT';
export const UTILITY_DEMAND_MAX_GET_CURRENT = 'UTILITY_DEMAND_MAX_GET_CURRENT';
export const UTILITY_DEMAND_MAX_GET_LAST = 'UTILITY_DEMAND_MAX_GET_LAST';

export default keyMirror({
  [`${UTILITY_DEMAND_GET_LAST}_START`]: null,
  [`${UTILITY_DEMAND_GET_LAST}_SUCCESS`]: null,
  [`${UTILITY_DEMAND_GET_LAST}_FAILURE`]: null,
  [`${UTILITY_DEMAND_GET_CURRENT}_START`]: null,
  [`${UTILITY_DEMAND_GET_CURRENT}_SUCCESS`]: null,
  [`${UTILITY_DEMAND_GET_CURRENT}_FAILURE`]: null,
  [`${UTILITY_DEMAND_MAX_GET_LAST}_START`]: null,
  [`${UTILITY_DEMAND_MAX_GET_LAST}_SUCCESS`]: null,
  [`${UTILITY_DEMAND_MAX_GET_LAST}_FAILURE`]: null,
  [`${UTILITY_DEMAND_MAX_GET_CURRENT}_START`]: null,
  [`${UTILITY_DEMAND_MAX_GET_CURRENT}_SUCCESS`]: null,
  [`${UTILITY_DEMAND_MAX_GET_CURRENT}_FAILURE`]: null
});
