import keyMirror from 'keymirror';

export default keyMirror({
  LOAD_SUBSCRIBE_EVENT_START: null,
  LOAD_SUBSCRIBE_EVENT_SUCCESS: null,
  LOAD_SUBSCRIBE_EVENT_FAILURE: null,

  LOAD_UNSUBSCRIBE_EVENT_START: null,
  LOAD_UNSUBSCRIBE_EVENT_SUCCESS: null,
  LOAD_UNSUBSCRIBE_EVENT_FAILURE: null,

  LOAD_USER_SUBSCRIPTION_INFO_START: null,
  LOAD_USER_SUBSCRIPTION_INFO_SUCCESS: null,
  LOAD_USER_SUBSCRIPTION_INFO_FAILURE: null
});
