import keyMirror from 'keymirror';

export default keyMirror({
  PORTFOLIO_DETAIL_PRIMARY_GET_START: null,
  PORTFOLIO_DETAIL_PRIMARY_GET_SUCCESS: null,
  PORTFOLIO_DETAIL_PRIMARY_GET_FAILURE: null,
  PORTFOLIO_DETAIL_PRIMARY_DATA_RESET: null,
  PORTFOLIO_DETAIL_COMPARISON_GET_START: null,
  PORTFOLIO_DETAIL_COMPARISON_GET_SUCCESS: null,
  PORTFOLIO_DETAIL_COMPARISON_GET_FAILURE: null,
  PORTFOLIO_DETAIL_COMPARISON_DATA_RESET: null,
  COMPARISON_DATE_SET: null,
  PRIMARY_DATE_SET: null
});
