import keyMirror from 'keymirror';

export default keyMirror({
  EMISSIONS_PRIMARY: null,
  EMISSIONS_PRIMARY_START: null,
  EMISSIONS_PRIMARY_SUCCESS: null,
  EMISSIONS_PRIMARY_FAILURE: null,
  EMISSIONS_PRIMARY_DATA_RESET: null,
  EMISSIONS_COMPARISON: null,
  EMISSIONS_COMPARISON_START: null,
  EMISSIONS_COMPARISON_SUCCESS: null,
  EMISSIONS_COMPARISON_FAILURE: null,
  EMISSIONS_COMPARISON_DATA_RESET: null,
  EMISSIONS_PRIMARY_DATE_SET: null,
  EMISSIONS_COMPARISON_DATE_SET: null
});
