name: CI

on:
  pull_request:
    branches: [master, staging, dev]

env:
  NPM_TOKEN: ${{ secrets.NIO_NPM_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Node version
        run: echo "NODE_VERSION=$(cat .nvmrc)" > $GITHUB_ENV
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run linters
        run: yarn lint --no-fix
      - name: Run Tests
        run: yarn test
